name: run
on:
  workflow_dispatch:

jobs:
  build:
    name: "Run on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: 4d/tool4d-action@main
      id: tool4drun
      with:
        project: "*"
        startup-method: main
        product-line: main
        version: main
        build: official
        token: ${{ secrets.DLTK }}
